name: Trigger Local Jenkins Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted   # Runs on Jenkins server
    steps:
      - name: Trigger Jenkins Job
        env:
            JENKINS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
            JENKINS_URL: http://localhost:8080
            JENKINS_USERNAME: exvbuild
            JENKINS_JOB_NAME: CMake_Build
        run: |
          echo "Triggering Jenkins job from GitHub Actions..."
          echo "Branch Name"
          echo ${GITHUB_REF_NAME}
          echo "Jenkins Token"
          echo ${{ secrets.JENKINS_ACCESS_TOKEN }}
          curl -X POST \
          "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/buildWithParameters?BRANCH_NAME=${GITHUB_REF_NAME}" \
          --user "${JENKINS_USERNAME}:${JENKINS_TOKEN}"
        
            

      - name: Wait for Jenkins job to complete
        run: |
          echo "Waiting for Jenkins job to complete..."
          sleep 60
          # Optional: poll Jenkins API for status

      - name: Notify GitHub PR (optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Posting build status to PR..."
          # You can use GitHub CLI or API here to comment on PR
