name: Trigger Local Jenkins Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted   # Runs on Jenkins server
    steps:
      - name: Trigger Jenkins Job
        run: |
          echo "Triggering Jenkins job from GitHub Actions..."
          echo "Branch Name"
          echo ${GITHUB_REF_NAME}
          echo "Jenkins Token"
          echo ${{ secrets.JENKINS_ACCESS_TOKEN }}
          curl --request POST \
          --url http://localhost:8080/job/CMake_Build/buildWithParameters?BRANCH_NAME=${GITHUB_REF_NAME}\
          --user exvbuild:${{ secrets.JENKINS_ACCESS_TOKEN }}
        env:
            JENKINS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
            

      - name: Wait for Jenkins job to complete
        run: |
          echo "Waiting for Jenkins job to complete..."
          sleep 60
          # Optional: poll Jenkins API for status

      - name: Notify GitHub PR (optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Posting build status to PR..."
          # You can use GitHub CLI or API here to comment on PR
