name: Trigger Local Jenkins Build

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    
env:
    JENKINS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
    JENKINS_URL: http://localhost:8080
    JENKINS_USERNAME: exvbuild
    JENKINS_JOB_NAME: CMake_Build
    #GIT_PR_ACCESS_TOKEN : ${{ secrets.PR_ACCESSS_TOKEN }}
    GIT_PR_ACCESS_TOKEN : ${{ secrets.PR_CLASSIC_ACCESS_TOKEN }}
    GIT_PR_AUTHORIZE_USERS : ${{ secrets.PR_AUTHORIZE_USERS }}
    

jobs:
  build:
    runs-on: self-hosted   # Runs on Jenkins server
    steps:
      - name: Trigger Jenkins Job
        id: trigger
        
        run: |
          echo "Triggering Jenkins job from GitHub Actions..."
          echo "Call jenkins Request : ${{ github.head_ref }}"

          ## Post Request to Build with pull request branch
          curl -X POST \
          "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/buildWithParameters?BRANCH_NAME=${{ github.head_ref }}" \
          --user "${JENKINS_USERNAME}:${JENKINS_TOKEN}"
            

      - name: Wait for Jenkins Job To Complete
        id: trigger_status
        run: |
          echo "Waiting for Jenkins job to complete..."
          MAX_ATTEMPTS=10
          SLEEP_SECONDS=5
          NEXT_BUILD_WAIT_SECONDS=2
          COUNTER=0

          # Call Jenkins to check the latest build 
          LATEST_BUILD=$(curl -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/lastBuild/api/json")
          LATEST_BUILD_URL=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['url'])" "$LATEST_BUILD")
          echo "Latest Build URL in Jenkins Waiting job: $LATEST_BUILD_URL"

          # Wait until build has started
          while true; do
            BUILD_INFO=$(curl -s -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} \
            "${LATEST_BUILD_URL}api/json")
            
            NEXT_BUILD=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['nextBuild'])" "$BUILD_INFO")

            if [[ "$NEXT_BUILD" == None ]]; then
              echo "Next build is loading..."
            else
              LATEST_BUILD_URL=$(python3 -c "import sys,ast; print(ast.literal_eval(sys.argv[1])['url'])" "$NEXT_BUILD")
              break
            fi
            sleep $NEXT_BUILD_WAIT_SECONDS
          done
          echo "build_url=$LATEST_BUILD_URL" >> $GITHUB_OUTPUT #set Latest Build URL in Github Output

          # Check the started build status
          while true; do
            BUILD_INFO=$(curl -s -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} \
            "${LATEST_BUILD_URL}api/json")

            STATUS=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['result'])" "$BUILD_INFO")
            BUILDING=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['building'])" "$BUILD_INFO")

            echo "Build Status $STATUS"
            echo "Is Building $BUILDING"

            if [[ "$BUILDING" == True ]]; then
              echo "Build is still running..."
            elif [[ "$STATUS" == "SUCCESS" ]]; then
              echo "Jenkins build succeeded!"
              echo "build_status=$STATUS" >> $GITHUB_OUTPUT #set Latest Build Status in Github Output
              break
            elif [[ "$STATUS" == "FAILURE" ]]; then
              echo "Jenkins build failed!"
              echo "build_status=$STATUS" >> $GITHUB_OUTPUT #set Latest Build Status in Github Output
              break
            elif [[ "$STATUS" == "ABORTED" ]]; then
              echo "Jenkins build aborted!"
              echo "build_status=$STATUS" >> $GITHUB_OUTPUT #set Latest Build Status in Github Output
              break
            else
              echo "Unknown status: $STATUS"
              exit 1
            fi
          
            COUNTER=$((COUNTER+1))
            if [[ $COUNTER -ge $MAX_ATTEMPTS ]]; then
              echo "Timed out waiting for Jenkins build."
              exit 1
            fi
          
            sleep $SLEEP_SECONDS
          done

      - name: Notify GitHub PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Posting build status to PR..."

          #Call Jenkins Console output and write it in console.txt
          BUILD_CONSOLE_OUTPUT=$(curl -s -u ${JENKINS_USERNAME}:${JENKINS_TOKEN} \
            "${{ steps.trigger_status.outputs.build_url }}consoleText" > console.txt)
          COMMENT_BODY=$(printf "**Jenkins Build Console Output (truncated)**\n\n%s" "$(head -n 1000 console.txt)")

          # Escape backslashes, double quotes, and newlines for JSON. Remove '>' and '+' characters from log
          JSON_BODY=$(printf '%s' "$COMMENT_BODY" | python3 -c 'import json,sys; remove_chars=set(">+"); s=json.dumps(sys.stdin.read()); s="".join(ch for ch in s if ch not in remove_chars); print(s)')

          #Comment the consoleText in a comment
          COMMENT_COMMAND=$(curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -d "{\"body\":$JSON_BODY}")

          BUILD_STATUS=${{ steps.trigger_status.outputs.build_status }}
          echo "Build Status : ${BUILD_STATUS}"
          #if build status is not success, comment the authorized users, else close the pull request
          if [[ "$BUILD_STATUS" != "SUCCESS" ]]; then
            ## Comment on PR with build authorized users
            PR_AUTH_USERS=$(printf '%s' "$GIT_PR_AUTHORIZE_USERS" | python3 -c 'import sys; users=[u.strip() for u in sys.stdin.read().strip().split(",")]; print(", ".join("@" + u for u in users))')
            COMMENT_ON_PR_BUILD_FAIL=$(curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
                -d "{\"body\": \"Build has FAILED. $PR_AUTH_USERS, Please review the PR!\"}")
              
            exit 1
          fi

  merge_pr:
    runs-on: self-hosted   # Runs on Jenkins server
    needs: build
    steps:
      - name: Merge PR
        run: |
          ## Merge the pull request automatically

          #Check pull request is mergable
          while true;do
            MERGEBLE_COMMAND=$(curl -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})

            IS_MERGEABLE=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['mergeable'])" "$MERGEBLE_COMMAND")
            

            if [[ "$IS_MERGEABLE" == None ]]; then
              echo "Still Checking Mergeable..."
            elif [[ "$IS_MERGEABLE" == False ]]; then
              COMMENT_ON_MERGE_FAIL=$(curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
                -d '{"body":"Unable to merge pull request automatically. Please review manually."}')
              break
              exit 1
            elif [[ "$IS_MERGEABLE" == True ]]; then
              echo "Merge checking is succeeded"
              break
            else
              echo "Unknown Response"
              break
              exit 1
            fi

            sleep 1 #1 second sleep
          done
          
          echo "Calling Merge Command"
          MERGE_COMMAND=$(curl -X PUT \
            -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -d '{"merge_method":"merge"}')
          

          IS_MERGE_SUCCESS=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['merged'])" "$MERGE_COMMAND")
          if [[ "$IS_MERGE_SUCCESS" == True ]]; then
              #Comment With user name 
              MERGE_GET_USER_COMMAND=$(curl -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})

              PR_USER_NAME=$(python3 -c "import sys, json; print(json.loads(sys.argv[1])['user']['login'])" "$MERGE_GET_USER_COMMAND")

              COMMENT_ON_MERGE_SUCCESS=$(curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
                -d "{\"body\": \"Hi @$PR_USER_NAME, your pull request has successfully merged!\"}")
          else
            COMMENT_ON_MERGE_FAIL=$(curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GIT_PR_ACCESS_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
              -d '{"body":"Unable to merge pull request automatically. Please review manually."}')  
            exit 1
          fi   
