name: Trigger Local Jenkins Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted   # Runs on Jenkins server
    steps:
      - name: Trigger Jenkins Job
        id: trigger
        env:
            JENKINS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
            JENKINS_URL: http://localhost:8080
            JENKINS_USERNAME: exvbuild
            JENKINS_JOB_NAME: CMake_Build
        run: |
          echo "Triggering Jenkins job from GitHub Actions..."
          echo "Call jenkins Request : ${{ github.head_ref }}"
          curl -X POST \
          "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/buildWithParameters?BRANCH_NAME=${{ github.head_ref }}" \
          --user "${JENKINS_USERNAME}:${JENKINS_TOKEN}"
        
            

      - name: Wait for Jenkins job to complete
        run: |
          echo "Waiting for Jenkins build to complete..."
          while true; do
          BUILD_INFO=$(curl -s -u $JENKINS_USERNAME:${JENKINS_TOKEN} \
            "${{ steps.trigger.outputs.build_url }}api/json")

          BUILDING=$(echo $BUILD_INFO | jq -r '.building')
          RESULT=$(echo $BUILD_INFO | jq -r '.result')

          if [[ "$BUILDING" == "false" ]]; then
            echo "Build finished with result: $RESULT"
            echo "result=$RESULT" >> $GITHUB_OUTPUT
            break
          fi
          echo "Still building..."
          sleep 5
          done

      - name: Notify GitHub PR (optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Posting build status to PR..."
          # You can use GitHub CLI or API here to comment on PR
